### ISSUE TITLE
http: panic serving 127.0.0.1:34200: runtime error: index out of range

### ISSUE THREAD

**Issue by lwhile** [lwhile/gogen#5]
```
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc4203626e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42036a680, 0xc4204be100, 0xc420405ce0, 0x768940, 0xc42036a698)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42036a680, 0xc42036a680, 0xc420436000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc42038e540, 0xc42006ef00)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc42038e540, 0xc42006ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc42038e540, 0xc42006ef00)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc42038e540, 0xc42006ed00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4203626e0, 0x9f3a40, 0xc420370140)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/11/05 15:59:58 http: panic serving 127.0.0.1:34201: runtime error: index out of range
goroutine 3 [running]:
net/http.(*conn).serve.func1(0xc420374000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e000, 0xc42007ce80, 0xc42007b320, 0xa3e968, 0x0)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e000, 0xc42007ce40, 0xc42007b2f0, 0xa3e968, 0x0)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:93 +0x253
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e000, 0xc42007ce00, 0xc42007b290, 0x768940, 0xc42007e018)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:93 +0x253
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42007e000, 0xc42007e000, 0xc420414000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc42015c0e0, 0xc4204c4400)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc42015c0e0, 0xc4204c4400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc42015c0e0, 0xc4204c4400)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc42015c0e0, 0xc42000a600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420374000, 0x9f3a40, 0xc420012580)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/11/05 15:59:58 http: panic serving 127.0.0.1:34202: runtime error: index out of range
goroutine 4 [running]:
net/http.(*conn).serve.func1(0xc4203740a0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e0d0, 0xc42007dac0, 0xc420195800, 0x768940, 0xc42007e0e8)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42007e0d0, 0xc42007e0d0, 0xc420116000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc42015c380, 0xc4204c4900)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc42015c380, 0xc4204c4900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc42015c380, 0xc4204c4900)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc42015c380, 0xc42000a500)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4203740a0, 0x9f3a40, 0xc420012400)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/11/05 15:59:58 http: panic serving 127.0.0.1:34203: runtime error: index out of range
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc420374140)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42036a000, 0xc42019cd40, 0xc4202102a0, 0x768940, 0xc42036a018)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42036a000, 0xc42036a000, 0xc420518000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc4201c20e0, 0xc42046e200)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc4201c20e0, 0xc42046e200)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc4201c20e0, 0xc42046e200)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc4201c20e0, 0xc42000a800)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420374140, 0x9f3a40, 0xc420012980)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/11/05 15:59:58 http: panic serving 127.0.0.1:34204: runtime error: index out of range
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc4203741e0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42036a1a0, 0xc4201ea980, 0xc42025e5a0, 0x768940, 0xc42036a1b8)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42036a1a0, 0xc42036a1a0, 0xc4205a2000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc4201c21c0, 0xc42046e700)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc4201c21c0, 0xc42046e700)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc4201c21c0, 0xc42046e700)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc4201c21c0, 0xc42000a700)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4203741e0, 0x9f3a40, 0xc420012800)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/11/05 15:59:58 http: panic serving 127.0.0.1:34232: runtime error: index out of range
goroutine 29 [running]:
net/http.(*conn).serve.func1(0xc4200aa640)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x79a9c0, 0xa17540)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e000, 0xc4201eb980, 0xc42022ec30, 0xa3e968, 0x0)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:76 +0x46f
github.com/lwhile/gogen.(*jsonParser).parse(0xc42007e000, 0xc4201eb900, 0xc42022ec00, 0x768940, 0xc42007e018)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:93 +0x253
github.com/lwhile/gogen.(*jsonParser).Parse(0xc42007e000, 0xc42007e000, 0xc4204c8000)
	/usr/local/go/src/github.com/lwhile/gogen/parser.go:59 +0x120
github.com/lwhile/gogen.genStruct(0x9f3440, 0xc42015c0e0, 0xc4204c4600)
	/usr/local/go/src/github.com/lwhile/gogen/handler.go:30 +0x274
net/http.HandlerFunc.ServeHTTP(0x85f4e8, 0x9f3440, 0xc42015c0e0, 0xc4204c4600)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203483c0, 0x9f3440, 0xc42015c0e0, 0xc4204c4600)
	/usr/local/go/src/github.com/gorilla/mux/mux.go:132 +0x101
net/http.serverHandler.ServeHTTP(0xc420320bb0, 0x9f3440, 0xc42015c0e0, 0xc4204c4400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200aa640, 0x9f3a40, 0xc4201eaac0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by lwhile** [comment]
Close
